### ISSUE TITLE
Not working with the new patch

### ISSUE THREAD

**Issue by Ciante79** [Pr3vention/UniversalBar#4]
The addon is not working with the new patch

It doesn't appear in the settings and it doesn't populate the previously saved bars anymore

Error:

398x UniversalBar/UniversalBarSettings.lua:132: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@UniversalBar/UniversalBarSettings.lua"]:132: in function `InitializeSettings'
[string "@UniversalBar/UniversalBar.lua"]:229: in function <UniversalBar/UniversalBar.lua:226>

Locals:
self = <table> {
 eventFrame = Frame {
 }
 L = <table> {
 }
}
title = FontString {
}
autoLoadAtLoginCheckbox = UniversalBarCheckAutoLoadAtLogin {
 Text = UniversalBarCheckAutoLoadAtLoginText {
 }
 text = UniversalBarCheckAutoLoadAtLoginText {
 }
 label = UniversalBarCheckAutoLoadAtLoginText {
 }
}
clearUnsavedActionSlots = UniversalBarCheckClearUnsavedActionSlots {
 Text = UniversalBarCheckClearUnsavedActionSlotsText {
 }
 text = UniversalBarCheckClearUnsavedActionSlotsText {
 }
 label = UniversalBarCheckClearUnsavedActionSlotsText {
 }
}
AutosaveSlotChangesCheckbox = UniversalBarCheckAutosaveSlotChanges {
 Text = UniversalBarCheckAutosaveSlotChangesText {
 }
 text = UniversalBarCheckAutosaveSlotChangesText {
 }
 label = UniversalBarCheckAutosaveSlotChangesText {
 }
}
unibar1 = UniversalBarCheckunibar1 {
 Text = UniversalBarCheckunibar1Text {
 }
 text = UniversalBarCheckunibar1Text {
 }
 label = UniversalBarCheckunibar1Text {
 }
}
unibar2 = UniversalBarCheckunibar2 {
 Text = UniversalBarCheckunibar2Text {
 }
 text = UniversalBarCheckunibar2Text {
 }
 label = UniversalBarCheckunibar2Text {
 }
}
unibar3 = UniversalBarCheckunibar3 {
 Text = UniversalBarCheckunibar3Text {
 }
 text = UniversalBarCheckunibar3Text {
 }
 label = UniversalBarCheckunibar3Text {
 }
}
unibar4 = UniversalBarCheckunibar4 {
 Text = UniversalBarCheckunibar4Text {
 }
 text = UniversalBarCheckunibar4Text {
 }
 label = UniversalBarCheckunibar4Text {
 }
}
unibar5 = UniversalBarCheckunibar5 {
 Text = UniversalBarCheckunibar5Text {
 }
 text = UniversalBarCheckunibar5Text {
 }
 label = UniversalBarCheckunibar5Text {
 }
}
unibar6 = UniversalBarCheckunibar6 {
 Text = UniversalBarCheckunibar6Text {
 }
 text = UniversalBarCheckunibar6Text {
 }
 label = UniversalBarCheckunibar6Text {
 }
}
unibar7 = UniversalBarCheckunibar7 {
 Text = UniversalBarCheckunibar7Text {
 }
 text = UniversalBarCheckunibar7Text {
 }
 label = UniversalBarCheckunibar7Text {
 }
}
unibar8 = UniversalBarCheckunibar8 {
 Text = UniversalBarCheckunibar8Text {
 }
 text = UniversalBarCheckunibar8Text {
 }
 label = UniversalBarCheckunibar8Text {
 }
}
saveBarConfigButton = UniversalBarSaveBarConfigButton {
 Right = Texture {
 }
 Left = Texture {
 }
 fitTextWidthPadding = 40
 Text = UniversalBarSaveBarConfigButtonText {
 }
 Middle = Texture {
 }
 fitTextCanWidthDecrease = true
}
loadBarConfigButton = UniversalBarLoadBarConfigButton {
 Right = Texture {
 }
 Left = Texture {
 }
 fitTextWidthPadding = 40
 Text = UniversalBarLoadBarConfigButtonText {
 }
 Middle = Texture {
 }
 fitTextCanWidthDecrease = true
}
clearBarConfigButton = UniversalBarClearBarConfigButton {
 Right = Texture {
 }
 Left = Texture {
 }
 fitTextWidthPadding = 40
 Text = UniversalBarClearBarConfigButtonText {
 }
 Middle = Texture {
 }
 fitTextCanWidthDecrease = true
}
(*temporary) = nil
(*temporary) = Frame {
 name = "UniversalBar"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
defaultOptions = <table> {
 AutosaveSlotChanges = false
 ClearUnsavedActionSlots = true
 Bars = <table> {
 }
 AutoLoadAtLogin = true
 BarConfig = <table> {
 }
}
frame = Frame {
 name = "UniversalBar"
}
addonName = "UniversalBar"
L = <table> {
 Bars = <table> {
 }
 Settings = <table> {
 }
 Errors = <table> {
 }
}
UniversalBar = <table> {
 eventFrame = Frame {
 }
 L = <table> {
 }
}

**Comment by Pr3vention** [comment]
Sorry for the delay on this. Been held up with work and had no time to keep up with patch changes. Version 1.1.4 should be available shortly on Curseforge, WoWInterface and Wago to address this.
