### ISSUE TITLE
Feature Request: Bonus Bars Support

### ISSUE THREAD

**Issue by neocryptek** [Pr3vention/UniversalBar#6]
Hi,

Would it be possible to please add support for bonus bars beyond the standard 8 action bars? Ex: dragonriding, druid forms, etc.

The slot ids for each bonus bar are listed here:
https://warcraft.wiki.gg/wiki/Action_Bar

Hoping it's just a matter of adding the slot ids config and adding a checkbox in the options to toggle them?

Thanks!

**Comment by Pr3vention** [comment]
Absolutely possible. A brief review has me thinking it won't take long at all to get working. Will take a look at this in a couple hours and report back.

**Comment by Pr3vention** [comment]
Working this on a separate branch. It's working for the most part, but I am finding unexpected oddities with certain actions. For example, playing the "Rake" on the action bar works but "Swipe" does not. The spellID for "Swipe" can sometimes be placed on your bar as 106785 (e.g. class trial character with default loadout), but the one you actually see the spellbook is 213764. While the feature works, I want to do a bit more testing being considering the merge.

**Comment by Pr3vention** [comment]
Should be available on Curseforge, WoWInterface and Wago now. Tested fairly extensively this morning but may have missed something for your use case. Please give it a try and let me know what you think!
